name = "reverse-proxy"
type = "javascript"
main = "index.js"  # This tells Wrangler that index.js is your entry file
account_id = "980533fa5bcb5f58d7da602f85df3040"  # Replace with your actual Cloudflare account ID
workers_dev = true
compatibility_date = "2025-03-09"
