name = "reverse-proxy-worker"
type = "javascript"
main = "index.js"  # This tells Wrangler that index.js is your entry file
account_id = "Abdullah.osama.elbagoury@gmail.com"  # Replace with your actual Cloudflare account ID
workers_dev = true
